org: estabraq
service: aws-project

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
            - "cognito-idp:*"
            - "dynamodb:*"
          Resource: "*"

plugins: 
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: courses
          method: post
          cors: true

  get_item:
    handler: handler.get_item
    events:
      - http:
          path: courses/{CourseID}
          method: get
          cors: true

  list_items:
    handler: handler.list_items
    events:
      - http:
          path: courses
          method: get
          cors: true

  login:
    handler: handler.login
    events:
      - http:
          path: login
          method: post
          cors: true

  get_enrolledCourses:
    handler: handler.get_enrolledCourses
    events:
      - http:
          path: get_enrolledCourses
          method: get
          cors: true

  get_user_details:
    handler: handler.get_user_details
    events:
      - http:
          path: get_userDetails
          method: get
          cors: true

  delete_course:
    handler: handler.delete_course
    events:
      - http:
          path: courses/delete
          method: post
          cors: true

  edit_course:
    handler: handler.edit_course
    events:
      - http:
          path: courses/edit
          method: post
          cors: true

  list_students:
    handler: handler.list_students
    events:
      - http:
          path: students
          method: get
          cors: true

  add_students_to_parent:
    handler: handler.add_students_to_parent
    events:
      - http:
          path: parents
          method: post
          cors: true

  add_file_to_student_reports:
    handler: handler.add_file_to_student_reports
    events:
      - http:
          path: reports
          method: post
          cors: true
  
  get_studentEnrolledCourses:
    handler: handler.get_studentEnrolledCourses
    events:
      - http:
          path: get_studentEnrolledCourses
          method: get
          cors: true
  get_teacherEnrolledCourses:
    handler: handler.get_teacherEnrolledCourses
    events:
      - http:
          path: get_teacherEnrolledCourses
          method: get
          cors: true
