org: estabraq
service: aws-project

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:*"
            - "cognito-idp:*"
            - "dynamodb:*"
          Resource: "*"

plugins: 
  - serverless-offline
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: courses
          method: post
          cors: true
  upload_file:
    handler: handler.create  # Since file upload is part of the create function
    events:
      - http:
          path: files/upload
          method: post
          cors: true
